version: '3.7'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    build: ./dockerfiles
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
    volumes:
      - $HOME/mongodb_data/db:$HOME/mongodb_data/db

  postgres_container:
      image: postgres:latest
      volumes:
        - $HOME/postgres_data/db:$HOME/postgres_data/db
      environment:
        - POSTGRES_PASSWORD=secret
        - POSTGRES_USER=postgres
      ports:
        - "5433:5433"

  neo4j_container:
      image: neo4j:latest
      volumes:
        - $HOME/neo4j_data/db:$HOME/neo4j_data/db
      ports:
        # http and bolt access respectively
        - 7474:7474
        - 7687:7687
      environment:
        - NEO4J_AUTH=neo4j/test