FROM puckel/docker-airflow:1.10.9
RUN pip install py2neo
RUN pip install pymongo
RUN pip install Click
RUN pip install pandas
RUN pip install psutil
RUN pip install Js2Py
RUN pip install psycopg2_binary
RUN pip install docker_py
